### ISSUE TITLE
Test DAJIN2 using the Build mappy on macOS ARM

### ISSUE THREAD

**Issue by akikuno** [akikuno/DAJIN2#46]
### 📋 Description

Recently, Bioconda supports macOS ARM (osx-arm64).

https://github.com/bioconda/bioconda-recipes/pull/49275

Until v0.5.2, translations were done using Rosetta 2, but now we need to check if DAJIN2 runs natively on osx-arm64.

### 🔍 Environment

```markdown
- DAJIN2 version: 0.5.2
- Python version: 3.10
```

**Comment by akikuno** [comment]
## ToDo

- [ ] Upgrade to v0.5.3 on BioConda
- [ ] Test installation and execution using M1 Mac Mini
- [ ] (If it works) Update Installation of README.md

**Comment by akikuno** [comment]
Test passed: https://github.com/akikuno/DAJIN2/actions/runs/10053078448
